[package]
name = "complate"
version = "0.0.0"
authors = ["Heiko Alexander Weber <haw@voidpointergroup.com>"]
edition = "2018"
license = "MIT"
description = "Standardizing messages the right way."
readme = "docs/README.md"
homepage = "https://replicadse.github.io/complate/"
repository = "https://github.com/replicadse/complate"
keywords = ["cli", "template", "replace", "standardizing"]
categories = ["command-line-utilities"]

[features]
  default = ["backend+cli"]
  "backend+cli" = ["dialoguer"]
  "backend+ui" = ["cursive", "fui"]

[profile]
  [dev]
    opt-level = 0
  [release]
    opt-level = 3

[dependencies]
async-trait = "0.1.24"
clap = "2.33.0"
handlebars = "3.0.1"

dialoguer = { version = "0.8.0", optional = true }
cursive = { version = "0.16", optional = true }
fui = { version = "2.0.0", optional = true }

bytes = "1.0.1"
futures = "0.3.1"
env_logger = "0.8.2"
mime = "0.3.16"

serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.45"
serde_yaml = "0.8.11"
json = "0.12.1"
