version: 0.6
templates:
    default:
        content:
            inline: |-
                {{ a.summary }} | {{ e.version }}
                Components: [{{ f.components }}]
                Author: {{ b.author.name }} | {{ c.author.account }}
                
                Files:
                {{ d.git.staged.files }}
        values:
            a.summary:
                prompt: "Enter the summary"
            b.author.name:
                shell: "git config user.name | tr -d '\n'"
            c.author.account:
                shell: "whoami | tr -d '\n'"
            d.git.staged.files:
                shell: "git diff --name-status --cached"
            e.version:
                select:
                    text: Select the version level that shall be incremented
                    options:
                        - "#patch"
                        - "#minor"
                        - "#major"
            f.components:
                check:
                    text: Select the components that are affected
                    options:
                        - security
                        - command::print
                        - backend::cli
                        - backend::ui
                        - misc
