version: 0.6
templates:
    0.default:
        content:
            inline: |-
                {{ a.summary }}
                Remarks: {{ b.remarks }}
                Components: {{ c.components }}
        values:
            a.summary:
                prompt: "Summary"
            b.remarks:
                prompt: "Remarks"
            c.components:
                check:
                    text: Select the components that are affected
                    options:
                        - security
                        - command:init
                        - command:print
                        - backend+cli
                        - backend+ui
                        - docs
                        - ci
                        - misc
    1.skrrrrrr:
        content:
            inline: |-
                skrrrr
