version: 0.7
templates:
    0.default:
        content:
            inline: |-
                {{ a.summary }}
                Remarks: {{ b.remarks }}
                Components: {{ c.components }}
        values:
            a.summary:
                prompt: "Summary"
            b.remarks:
                prompt: "Remarks"
            c.components:
                check:
                    text: Select the components that are affected
                    options:
                        - display: security
                          value: security
                        - display: command:init
                          value: command:init
                        - display: command:render
                          value: command:render
                        - display: backend+cli
                          value: backend+cli
                        - display: backend+ui
                          value: backend+ui
                        - display: docs
                          value: docs
                        - display: ci
                          value: ci
                        - display: misc
                          value: misc
    1.skrrrrrr:
        content:
            inline: |-
                skrrrr
