templates:
    internal:
        content:
            inline: |-
                {{ summary }} | {{ version }}
                {{ git.author }}
                Components: {{ components }}
                Author: {{ author }}
                
                Files:
                {{ git.staged.files }}
        values:
            author:
                static: "Weber, Heiko Alexander"
            summary:
                prompt: "Enter the summary"
            git.author:
                shell: "printf $(whoami)"
            git.staged.files:
                shell: "git diff --name-status --cached"
            version:
                select:
                    - "#patch"
                    - "#minor"
                    - "#major"
            components:
                check:
                    - Security
                    - ValueProvider
                    - Misc

    feature:
        content:
            file: "./.complate/feature.cpl"
        values:
            author:
                static: "Weber, Heiko Alexander"
            summary:
                prompt: "Enter the summary"
            git.staged.files:
                shell: "git diff --name-status --cached"
