version: 0.5

templates:
    default:
        content:
            inline: |-
                {{ summary }} | {{ version }}
                Components: [{{ components }}]
                Author: {{ author.name }} | {{ author.account }}
                
                Files:
                {{ git.staged.files }}
        values:
            summary:
                prompt: "Enter the summary"
            author.name:
                shell: "git config user.name"
            author.account:
                shell: "whoami | tr -d '\n'"
            git.staged.files:
                shell: "git diff --name-status --cached"
            version:
                select:
                    text: Select the version level that shall be incremented
                    options:
                        - "#patch"
                        - "#minor"
                        - "#major"
            components:
                check:
                    text: Select the components that are affected
                    options:
                        - Security
                        - ValueProvider
                        - CLI
                        - Misc
