version: 0.7
templates:
    0.default:
        content:
            inline: |-
                {{ a.summary }}
                Remarks: {{ b.remarks }}
                Components: {{ c.components }}
                Yes/No: {{ d.select }}
        values:
            a.summary:
                prompt: "Summary"
            b.remarks:
                prompt: "Remarks"
            c.components:
                check:
                    text: Select the components that are affected
                    options:
                        security:
                          display: security
                          value:
                            static: security
                        myself:
                          display: myself
                          value:
                            shell: whoami
            d.select:
              select:
                text: "???"
                options:
                  yes:
                    display: yes
                    value:
                      static: yes
                  no:
                    display: no
                    value:
                      shell: printf "no, no way!"
    1.skrrrrrr:
        content:
            inline: |-
                skrrrr
