templates:
    internal:
        content:
            inline: |-
                {{ summary }} | {{ version }}
                {{ components }}
                {{ author }}
                {{ git.staged.files }}
        values:
            author:
                static: "Weber, Heiko Alexander <heiko.a.weber@gmail.com>"
            summary:
                prompt: "Enter the summary"
            git.staged.files:
                shell: "git diff --name-status --cached"
            version:
                select:
                    - "#patch"
                    - "#minor"
                    - "#major"
            components:
                check:
                    - Security
                    - ValueProvider
                    - Misc

    feature:
        content:
            file: "./.complate/feature.cpl"
        values:
            author:
                static: "Weber, Heiko Alexander <heiko.a.weber@gmail.com>"
            summary:
                prompt: "Enter the summary"
            git.staged.files:
                shell: "git diff --name-status --cached"
