name: release

on:
  release:
    types: [published]

jobs:
  cargo-io:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.TAG }}
        name: crates.io
        runs-on: ubuntu-latest
        steps:
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::$(git tag --points-at HEAD --sort -version:refname | head -1)
    - name: Publish
      id: publish
      run: |
        VERSION=${{ steps.get_version.outputs.VERSION }} make update-version && 
        cargo login ${{ secrets.CRATES_IO_TOKEN }} && 
        cargo publish --allow-dirty
